baseURL = "http://hugotest.bep.is"
languageCode = "en-us"
title = "Hugo Test Site"
paginate = 4
pygmentscodefences = "true"
pygmentscodefencesguesssyntax = false
pygmentsstyle = "trac"
pygmentsuseclasses = false

googleAnalytics = "UA-52478213-6"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "Lanczos"

# Defatult JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"

[permalinks]
  section3 = "/:sections/:year/:month/:slug/"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true
anonymizeIP = true
[privacy.instagram]
disable = false
simple = false
[privacy.speakerDeck]
disable = true
[privacy.twitter]
disable = false
enableDNT = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = false
privacyEnhanced = true

[services]
[services.instagram]
disableInlineCSS = false

[languages]

[languages.en]
languageName = "English"
weight = 1
title = "Hugo Test in English"

[languages.nn]
languageName = "Nynorsk"
weight = 2
title = "Hugo Test på norsk"
contentDir = "content_nn"
