baseURL = "http://hugotest.bep.is"
languageCode = "en-us"
title = "Hugo Test Site"
paginate = 2
pygmentscodefences = "true"
pygmentscodefencesguesssyntax = false
pygmentsstyle = "trac"
pygmentsuseclasses = false

[permalinks]
  bundles = "/:year/:month/:slug/"