baseURL = "http://hugotest.bep.is"
languageCode = "en-us"
title = "Hugo Test Site"
paginate = 2
pygmentscodefences = "true"
pygmentscodefencesguesssyntax = false
pygmentsstyle = "trac"
pygmentsuseclasses = false


[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Defatult JPEG quality setting. Default is 75.
quality = 68

[permalinks]
  section3 = "/:sections/:year/:month/:slug/"